"""
ProFTPD Configuration Generator

Generates users.conf and ftpd.passwd files based on database settings.
"""

from .models import FTPUser, Folder, FolderAccess


def generate_proftpd_config():
    """Generate ProFTPD user configuration file content

    This generates only user-specific settings to be included via:
    Include /etc/proftpd/conf.d/*.conf

    Server settings (ServerType, Port, etc.) should be in main proftpd.conf
    """

    users = FTPUser.objects.filter(is_active=True).prefetch_related('folder_access__folder')
    folders = Folder.objects.all()

    config = '''# ProFTPD User Configuration
# Generated by ProFTPD Control Panel
# DO NOT EDIT MANUALLY - changes will be overwritten
#
# Include this file in proftpd.conf:
#   Include /etc/proftpd/conf.d/*.conf

# Virtual users authentication
AuthUserFile /etc/proftpd/ftpd.passwd
AuthOrder mod_auth_file.c

# Security settings for virtual users
RequireValidShell off

'''

    # Generate directory access rules for each folder
    for folder in folders:
        access_rules = FolderAccess.objects.filter(folder=folder).select_related('user')

        if not access_rules.exists():
            continue

        read_users = []
        write_users = []

        for access in access_rules:
            if not access.user.is_active:
                continue
            if access.permission == 'read':
                read_users.append(access.user.username)
            elif access.permission == 'write':
                write_users.append(access.user.username)
                read_users.append(access.user.username)  # write implies read

        if read_users or write_users:
            config += f'''
# Access rules for: {folder.name}
<Directory {folder.path}>
'''
            if read_users:
                config += f'''  <Limit READ DIRS>
    AllowUser {" ".join(read_users)}
    DenyAll
  </Limit>
'''
            if write_users:
                config += f'''  <Limit WRITE STOR DELE MKD RMD>
    AllowUser {" ".join(write_users)}
    DenyAll
  </Limit>
'''
            else:
                config += f'''  <Limit WRITE STOR DELE MKD RMD>
    DenyAll
  </Limit>
'''
            config += '</Directory>\n'

    return config


def generate_ftpusers_file():
    """
    Generate ftpd.passwd file for ProFTPD virtual users

    Format: username:password_hash:uid:gid:gecos:homedir:shell
    """
    users = FTPUser.objects.filter(is_active=True)

    lines = [
        "# ProFTPD virtual users file",
        "# Generated by ProFTPD Control Panel",
        "# Format: username:password:uid:gid:gecos:homedir:shell",
    ]

    # Use a common UID/GID for virtual users (typically ftp user)
    uid = "1000"
    gid = "1000"
    shell = "/bin/false"

    for user in users:
        # Get first accessible folder as home dir, or /tmp if none
        first_access = user.folder_access.first()
        home_dir = first_access.folder.path if first_access else "/tmp"

        line = f"{user.username}:{user.password_hash}:{uid}:{gid}:{user.username}:{home_dir}:{shell}"
        lines.append(line)

    return "\n".join(lines)


def generate_user_config(user):
    """Generate config snippet for a specific user"""
    config = f"# Configuration for user: {user.username}\n"

    for access in user.folder_access.all():
        perm_str = "Read & Write" if access.permission == 'write' else "Read Only"
        config += f"# - {access.folder.path}: {perm_str}\n"

    return config
