# Generated by Django 5.2.10 on 2026-01-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftpmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpuser',
            name='systemuser',
            field=models.CharField(default='1001', help_text='System username or UID for file ownership', max_length=100),
        ),
    ]
