# Generated by Django 5.2.10 on 2026-01-20 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftpmanager', '0002_ftpuser_systemuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basedir', models.CharField(default='/main/', help_text='Base directory for folder lookup', max_length=500)),
                ('exclude_dirs', models.CharField(default='/keys/,.ssh', help_text='Comma-separated list of directories to exclude', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
