# Generated by Django 5.2.10 on 2026-01-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftpmanager', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='systemuser_regexp',
            field=models.CharField(default='.*\\..*', help_text='Regexp to filter system users (default: names with at least one dot)', max_length=200),
        ),
    ]
