import pytest
import sys
from unittest.mock import patch, MagicMock

from ftpmanager.models import FTPUser, Folder, FolderAccess
from ftpmanager.config_generator import (
    generate_proftpd_config,
    generate_ftpusers_file,
    generate_user_config,
    get_uid_gid,
)


class TestGenerateProftpdConfig:
    """Tests for generate_proftpd_config function"""

    def test_empty_database(self, db):
        """Test config generation with no users or folders"""
        config = generate_proftpd_config()

        assert '# ProFTPD User Configuration' in config
        assert 'AuthUserFile /etc/proftpd/ftpd.passwd' in config
        assert 'RequireValidShell off' in config

    def test_folder_with_no_access_rules(self, db, folder):
        """Test that folders without access rules are skipped"""
        config = generate_proftpd_config()

        assert folder.path not in config

    def test_folder_with_read_access(self, db, ftp_user, folder):
        """Test config for folder with read-only access"""
        FolderAccess.objects.create(user=ftp_user, folder=folder, permission='read')

        config = generate_proftpd_config()

        assert f'<Directory {folder.path}>' in config
        assert '<Limit READ DIRS>' in config
        assert f'AllowUser {ftp_user.username}' in config
        # Should deny write for read-only
        assert '<Limit WRITE STOR DELE MKD RMD>' in config

    def test_folder_with_write_access(self, db, ftp_user, folder):
        """Test config for folder with write access"""
        FolderAccess.objects.create(user=ftp_user, folder=folder, permission='write')

        config = generate_proftpd_config()

        assert f'<Directory {folder.path}>' in config
        # Write implies read
        assert '<Limit READ DIRS>' in config
        assert '<Limit WRITE STOR DELE MKD RMD>' in config
        assert f'AllowUser {ftp_user.username}' in config

    def test_write_permission_implies_read(self, db, ftp_user, folder):
        """Test that write permission also grants read access"""
        FolderAccess.objects.create(user=ftp_user, folder=folder, permission='write')

        config = generate_proftpd_config()

        # User should appear in both READ and WRITE limits
        read_section_start = config.find('<Limit READ DIRS>')
        write_section_start = config.find('<Limit WRITE STOR')

        # Both sections should contain the username
        assert ftp_user.username in config[read_section_start:write_section_start]

    def test_inactive_user_excluded(self, db, inactive_ftp_user, folder):
        """Test that inactive users are excluded from config"""
        FolderAccess.objects.create(user=inactive_ftp_user, folder=folder, permission='read')

        config = generate_proftpd_config()

        # The folder should not have a Directory block since the only user is inactive
        assert f'<Directory {folder.path}>' not in config

    def test_multiple_users_same_folder(self, db, ftp_user, folder):
        """Test config with multiple users having access to same folder"""
        user2 = FTPUser.objects.create(username='ftpuser2', systemuser='1002', is_active=True)
        FolderAccess.objects.create(user=ftp_user, folder=folder, permission='read')
        FolderAccess.objects.create(user=user2, folder=folder, permission='write')

        config = generate_proftpd_config()

        assert f'<Directory {folder.path}>' in config
        # Both users should be in read list (write implies read)
        assert 'ftpuser1' in config
        assert 'ftpuser2' in config

    def test_multiple_folders(self, db, ftp_user, folder, folder2):
        """Test config with multiple folders"""
        FolderAccess.objects.create(user=ftp_user, folder=folder, permission='read')
        FolderAccess.objects.create(user=ftp_user, folder=folder2, permission='write')

        config = generate_proftpd_config()

        assert f'<Directory {folder.path}>' in config
        assert f'<Directory {folder2.path}>' in config

    def test_config_header(self, db):
        """Test that config has proper header comments"""
        config = generate_proftpd_config()

        assert '# ProFTPD User Configuration' in config
        assert '# Generated by ProFTPD Control Panel' in config
        assert '# DO NOT EDIT MANUALLY' in config


class TestGetUidGid:
    """Tests for get_uid_gid function"""

    def test_numeric_uid(self):
        """Test with numeric UID string"""
        # Mock pwd module to avoid import error on Windows
        mock_pwd = MagicMock()
        with patch.dict('sys.modules', {'pwd': mock_pwd}):
            uid, gid = get_uid_gid('1001')
            assert uid == '1001'
            assert gid == '1001'

    def test_numeric_uid_different_value(self):
        """Test with different numeric UID"""
        mock_pwd = MagicMock()
        with patch.dict('sys.modules', {'pwd': mock_pwd}):
            uid, gid = get_uid_gid('33')
            assert uid == '33'
            assert gid == '33'

    def test_username_lookup_success(self):
        """Test successful username lookup"""
        mock_pwd = MagicMock()
        mock_pwnam = MagicMock()
        mock_pwnam.pw_uid = 1000
        mock_pwnam.pw_gid = 1000
        mock_pwd.getpwnam.return_value = mock_pwnam

        with patch.dict('sys.modules', {'pwd': mock_pwd}):
            uid, gid = get_uid_gid('www-data')

            mock_pwd.getpwnam.assert_called_once_with('www-data')
            assert uid == '1000'
            assert gid == '1000'

    def test_username_lookup_different_uid_gid(self):
        """Test username lookup with different UID and GID"""
        mock_pwd = MagicMock()
        mock_pwnam = MagicMock()
        mock_pwnam.pw_uid = 33
        mock_pwnam.pw_gid = 33
        mock_pwd.getpwnam.return_value = mock_pwnam

        with patch.dict('sys.modules', {'pwd': mock_pwd}):
            uid, gid = get_uid_gid('www-data')

            assert uid == '33'
            assert gid == '33'

    def test_username_not_found_fallback(self):
        """Test fallback to default when user not found"""
        mock_pwd = MagicMock()
        mock_pwd.getpwnam.side_effect = KeyError('User not found')

        with patch.dict('sys.modules', {'pwd': mock_pwd}):
            uid, gid = get_uid_gid('nonexistent')

            assert uid == '1001'
            assert gid == '1001'


class TestGenerateFtpusersFile:
    """Tests for generate_ftpusers_file function"""

    def test_empty_database(self, db):
        """Test ftpusers file with no users"""
        content = generate_ftpusers_file()

        assert '# ProFTPD virtual users file' in content
        assert '# Format: username:password:uid:gid:gecos:homedir:shell' in content

    def test_single_user_no_folder_access(self, db, ftp_user):
        """Test user with no folder access gets /tmp as home"""
        mock_pwd = MagicMock()
        mock_pwd.getpwnam.side_effect = KeyError('User not found')

        with patch.dict('sys.modules', {'pwd': mock_pwd}):
            content = generate_ftpusers_file()

        lines = content.split('\n')
        user_line = [l for l in lines if l.startswith('ftpuser1:')][0]

        parts = user_line.split(':')
        assert parts[0] == 'ftpuser1'  # username
        assert parts[1].startswith('$6$')  # password hash
        assert parts[5] == '/tmp'  # home dir fallback
        assert parts[6] == '/bin/false'  # shell

    def test_user_with_folder_access(self, db, ftp_user, folder, folder_access_read):
        """Test user with folder access gets folder path as home"""
        mock_pwd = MagicMock()
        mock_pwd.getpwnam.side_effect = KeyError('User not found')

        with patch.dict('sys.modules', {'pwd': mock_pwd}):
            content = generate_ftpusers_file()

        lines = content.split('\n')
        user_line = [l for l in lines if l.startswith('ftpuser1:')][0]

        parts = user_line.split(':')
        assert parts[5] == folder.path  # home dir is first accessible folder

    def test_inactive_user_excluded(self, db, inactive_ftp_user):
        """Test that inactive users are excluded"""
        content = generate_ftpusers_file()

        assert 'inactiveuser' not in content

    @patch('ftpmanager.config_generator.get_uid_gid')
    def test_uid_gid_from_systemuser(self, mock_get_uid_gid, db, ftp_user):
        """Test that UID/GID is obtained from systemuser field"""
        mock_get_uid_gid.return_value = ('1001', '1001')

        content = generate_ftpusers_file()

        mock_get_uid_gid.assert_called()
        lines = content.split('\n')
        user_line = [l for l in lines if l.startswith('ftpuser1:')][0]

        parts = user_line.split(':')
        assert parts[2] == '1001'  # uid
        assert parts[3] == '1001'  # gid

    def test_multiple_users(self, db, ftp_user):
        """Test with multiple users"""
        user2 = FTPUser.objects.create(username='ftpuser2', systemuser='1002', is_active=True)
        user2.set_password('pass2')
        user2.save()

        mock_pwd = MagicMock()
        mock_pwd.getpwnam.side_effect = KeyError('User not found')

        with patch.dict('sys.modules', {'pwd': mock_pwd}):
            content = generate_ftpusers_file()

        assert 'ftpuser1:' in content
        assert 'ftpuser2:' in content

    def test_file_format(self, db, ftp_user):
        """Test the file format is correct"""
        mock_pwd = MagicMock()
        mock_pwd.getpwnam.side_effect = KeyError('User not found')

        with patch.dict('sys.modules', {'pwd': mock_pwd}):
            content = generate_ftpusers_file()

        lines = content.split('\n')
        user_line = [l for l in lines if l.startswith('ftpuser1:')][0]

        parts = user_line.split(':')
        assert len(parts) == 7  # username:password:uid:gid:gecos:homedir:shell


class TestGenerateUserConfig:
    """Tests for generate_user_config function"""

    def test_user_with_no_access(self, db, ftp_user):
        """Test config for user with no folder access"""
        config = generate_user_config(ftp_user)

        assert f'# Configuration for user: {ftp_user.username}' in config

    def test_user_with_read_access(self, db, ftp_user, folder, folder_access_read):
        """Test config for user with read access"""
        config = generate_user_config(ftp_user)

        assert f'# Configuration for user: {ftp_user.username}' in config
        assert f'# - {folder.path}: Read Only' in config

    def test_user_with_write_access(self, db, ftp_user, folder2, folder_access_write):
        """Test config for user with write access"""
        config = generate_user_config(ftp_user)

        assert f'# - {folder2.path}: Read & Write' in config

    def test_user_with_multiple_folders(self, db, ftp_user, folder, folder2, folder_access_read, folder_access_write):
        """Test config for user with multiple folder access"""
        config = generate_user_config(ftp_user)

        assert f'# - {folder.path}: Read Only' in config
        assert f'# - {folder2.path}: Read & Write' in config
